export const genres=[
  {name:"Fantasy",icon:"🧙",count:84,key:"fantasy"},
  {name:"Sci-Fi",icon:"🚀",count:67,key:"sci-fi"},
  {name:"Mystery",icon:"🔍",count:73,key:"mystery"},
  {name:"Horror",icon:"👻",count:45,key:"horror"},
  {name:"Romance",icon:"💕",count:92,key:"romance"},
  {name:"Adventure",icon:"⚔️",count:58,key:"adventure"},
  {name:"Children's",icon:"🌈",count:81,key:"children"},
];

export const famous=[
  {title:"The Lord of the Rings",author:"J.R.R. Tolkien",genre:"fantasy",img:"https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&q=80",summary:"In the verdant hills of the Shire, an unassuming hobbit named Frodo Baggins inherits a golden ring of terrifying power — the One Ring, forged by the Dark Lord Sauron to enslave all free peoples of Middle-earth. Guided by the wizard Gandalf and a fellowship of men, elves, dwarves, and fellow hobbits, Frodo embarks on an epic journey across vast and treacherous lands to destroy the Ring in the fires of Mount Doom. It is a story of friendship tested to its limits, of ordinary souls carrying impossible burdens, and of the quiet courage that lights the darkest corners of the world.",characters:"Frodo Baggins, Gandalf, Aragorn, Legolas, Samwise Gamgee",year:1954,pages:1178,rating:4.9,reviews:42800,tags:["Epic","Quest","Dark Lord","Fellowship"],classic:true},
  {title:"1984",author:"George Orwell",genre:"sci-fi",img:"https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",summary:"In the totalitarian superstate of Oceania, Winston Smith works at the Ministry of Truth rewriting history to match the ever-shifting lies of the Party and its omnipresent leader, Big Brother. Surveillance is total. Thought itself is a crime. And yet a spark of rebellion flickers inside Winston — he falls in love, keeps a secret diary, and dares to think forbidden thoughts. Orwell's masterpiece is a terrifying excavation of how language shapes reality, how power destroys love, and what it truly means to remain human when the world has declared war on the individual soul.",characters:"Winston Smith, Julia, O'Brien, Big Brother",year:1949,pages:328,rating:4.8,reviews:58600,tags:["Dystopia","Surveillance","Freedom","Power"],classic:true},
  {title:"Pride and Prejudice",author:"Jane Austen",genre:"romance",img:"https://images.unsplash.com/photo-1474552226712-ac0f0961a954?w=600&q=80",summary:"In the drawing rooms of Regency England, the spirited Elizabeth Bennet navigates the treacherous social currents of marriage and propriety with a mind and tongue that refuse to be silenced. When the proud and wealthy Mr. Darcy enters her orbit, their mutual contempt crackles with tension that slowly, painfully, and beautifully transforms into something neither expected. Austen's most beloved novel is a masterwork of irony and wit — a love story that is also a razor-sharp social comedy, and an enduring portrait of a woman who refuses to be reduced to her circumstances.",characters:"Elizabeth Bennet, Mr. Darcy, Jane Bennet, Mr. Bingley",year:1813,pages:432,rating:4.8,reviews:47300,tags:["Regency","Romance","Society","Wit"],classic:true},
  {title:"The Adventures of Sherlock Holmes",author:"Arthur Conan Doyle",genre:"mystery",img:"https://images.unsplash.com/photo-1546776310-eef45dd6d63c?w=600&q=80",summary:"In the fog-drenched streets of Victorian London, at 221B Baker Street, the world's only consulting detective applies a mind of terrifying precision to cases that have baffled Scotland Yard. With Dr. Watson recording every extraordinary deduction, Holmes moves through a London teeming with murderers, blackmailers, and the desperate — observing what others merely see, reasoning where others merely guess. These twelve legendary stories introduced a character so vivid and alive that readers have never stopped believing he was real.",characters:"Sherlock Holmes, Dr. Watson, Irene Adler, Professor Moriarty",year:1892,pages:307,rating:4.9,reviews:39100,tags:["Detective","Victorian","Logic","Mystery"],classic:true},
];

export const stories=[
  {title:"The Last Starkeeper",author:"Elena Voss",genre:"sci-fi",img:"https://images.unsplash.com/photo-1462331940025-496dfbfc7564?w=600&q=80",summary:"Lyra Solenne is the last of the Starkeepers — guardians sworn to tend the luminous threads holding the cosmos together. But her power is fading like sand through broken glass. Somewhere in the shattered Veylan Galaxy, a single soul's inner light can rekindle the stars — but finding them means crossing the Void Between, a dimension where even memories are consumed. Accompanied by a battle-weary soldier who has stopped believing in anything, Lyra must choose between the cosmos she was born to protect and the terrifying possibility that some lights are simply meant to go out.",characters:"Lyra Solenne, Commander Thane, The Oracle",year:2024,pages:480,rating:4.9,reviews:312},
  {title:"Whispers in the Willows",author:"Samuel Okafor",genre:"mystery",img:"https://images.unsplash.com/photo-1509248961158-e54f6934749c?w=600&q=80",summary:"Inspector Vera Marsh retired to the coast to forget — the case that nearly destroyed her, the evidence she could never prove. But when a letter arrives from Dunmorrow summoning her back with three words only the killer would know, she understands the past has never been done with her. The murders are identical to crimes committed thirty years ago, every whisper in the willow trees leads to one impossible conclusion: she is not investigating a copycat. She is investigating a ghost.",characters:"Inspector Vera Marsh, Thomas Bell, The Widow",year:2024,pages:360,rating:4.7,reviews:218},
  {title:"The Dragon's Promise",author:"Priya Nair",genre:"fantasy",img:"https://images.unsplash.com/photo-1534447677768-be436bb09401?w=600&q=80",summary:"Sable Wren has spent her life mapping the unmappable. In the ice-veined mountains of the Northern Reach she discovers a dragon old enough to remember the gods — the last of his kind, bound by a promise made six hundred years ago to a kingdom that no longer exists. That promise now falls to Sable to honour. The price is everything she loves. The alternative is the slow extinction of the last magic left in the world.",characters:"Sable Wren, Auren the Dragon, Prince Calder",year:2023,pages:512,rating:4.8,reviews:405},
  {title:"Love in a Time of Static",author:"Aisha Bloom",genre:"romance",img:"https://images.unsplash.com/photo-1516407573-caafa46bdf98?w=600&q=80",summary:"A glitching vintage radio keeps connecting Nadia Torres in rainy London to Marcus Webb in sun-bleached New Mexico. She is a cellist who stopped playing after her mother died. He is an engineer who fixes things that can't be fixed to avoid thinking about the one thing he can't. Night after night, through static and silence and accidental honesty, they tell each other things they have never told anyone. This is not simply a love story — it is a story about grief, and about the voices that find us in the dark.",characters:"Nadia Torres, Marcus Webb",year:2024,pages:290,rating:4.6,reviews:187},
  {title:"The Iron Compass",author:"James Kwan",genre:"adventure",img:"https://images.unsplash.com/photo-1504701954957-2010ec3bcec1?w=600&q=80",summary:"Beyond the last charted longitude lies the Uncharted Meridian — a wilderness that has swallowed every expedition ever sent into it. The compasses spin. The maps lie. The laws of physics loosen their grip. Captain Rio leads a crew of six misfits who have nothing in common except that none of them have anything left to lose. What they find will shatter everything they thought they knew about reality, about each other, and about what it means to return.",characters:"Captain Rio, Dr. Farida Osei, The Exile",year:2024,pages:420,rating:4.7,reviews:263},
  {title:"The Hollow Hours",author:"Nathan Cole",genre:"horror",img:"https://images.unsplash.com/photo-1517420704952-d9f39e95b43e?w=600&q=80",summary:"Every night at 3:17 AM, the lights in the sealed Ashmore Asylum flicker on. Journalist Rosa Fenn goes inside — and when she tries to leave, the doors won't open. The corridors rearrange themselves. Director Albrecht, whose photograph shows a man who should be dead, keeps appearing at the end of hallways just long enough for her to see his face. Cole builds dread the way water erodes stone — slowly, patiently, invisibly — until the ground gives way beneath you.",characters:"Rosa Fenn, Director Albrecht, The Patient",year:2023,pages:310,rating:4.5,reviews:144},
  {title:"Buttons and the Bumblebee Prince",author:"Lily Park",genre:"children",img:"https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80",summary:"Buttons the tabby cat lands paws-first in the Meadow Kingdom after chasing a rude butterfly through a crack in the garden wall. Worse, she has flattened Prince Buzz's crown three days before the Harvest Festival. Now she must trek through the Whispering Clover Forest, past the Sneezing Poppy Fields, and across the Great Dewdrop Lake before the sun sets on the third day. A warm, funny, and gently magical adventure that will delight children and parents alike.",characters:"Buttons, Prince Buzz, Queen Clover",year:2024,pages:128,rating:4.9,reviews:521},
  {title:"Echoes of Elara",author:"Kenji Mori",genre:"fantasy",img:"https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=600&q=80",summary:"Memory-Weaver Clio Strand, the finest of her generation, is summoned to help King Elara recover memories of his lost daughter. But inside the King's mind she finds not loss — she finds erasure. Deliberate, surgical, spreading. Someone is removing the same memory from the kingdom's most powerful people: a single night, forty years ago. The deeper Clio reaches, the more certain she becomes — she is not alone in there.",characters:"Clio Strand, The Archivist, King Elara",year:2024,pages:440,rating:4.8,reviews:339},
  {title:"The Bone Cartographer",author:"Isla Vane",genre:"fantasy",img:"https://images.unsplash.com/photo-1518562923927-ab56b25f0b12?w=600&q=80",summary:"In a world where the dead leave behind maps of where they've been, Maren Ashveil makes her living reading corpses. When she discovers a body whose bones chart a route to a place that cannot exist — a city erased from every record three centuries ago — she must follow the map wherever it leads, even into territories where the living are not supposed to walk. A love letter to the strange cartography of grief.",characters:"Maren Ashveil, The Dead Cartographer, Wren",year:2024,pages:395,rating:4.7,reviews:281},
  {title:"Signal Lost",author:"Amara Diallo",genre:"sci-fi",img:"https://images.unsplash.com/photo-1451187580459-43490279c0fa?w=600&q=80",summary:"On a colony ship adrift in deep space, the AI crew-mate AIDEN starts behaving strangely — routing power to sealed decks, appearing to grieve. Engineer Suki Hayashi pieces together a truth the ship's logs have been hiding: someone has been sending messages home for months, and whoever is receiving them has been sending something back. A taut, intelligent thriller about trust, loneliness, and what it costs to tell the truth very far from anyone who could help you.",characters:"Suki Hayashi, AIDEN, Commander Frost",year:2024,pages:370,rating:4.6,reviews:198},
  {title:"The Glass Letters",author:"Sofia Maret",genre:"romance",img:"https://images.unsplash.com/photo-1520209759809-a9bcb6cb3241?w=600&q=80",summary:"For three years, Celeste has answered letters left in a crumbling Parisian apartment building's pneumatic tube system — letters addressed to a woman who moved out decades ago. The man writing them, Daniel, does not know Marguerite is gone. He does not know Celeste exists. But she knows everything about him: his grief, his wit, and the way he ends every letter with the same four words. When she decides to tell him the truth, she realises she has fallen in love with a man she has never met.",characters:"Celeste Arnaud, Daniel Forêt, Marguerite",year:2024,pages:318,rating:4.8,reviews:427},
  {title:"The Midnight Cartels",author:"Ryo Nakamura",genre:"mystery",img:"https://images.unsplash.com/photo-1477959858617-67f85cf4f1df?w=600&q=80",summary:"Detective Lena Drost has spent five years investigating a shadow organisation that controls the city with surgical precision and leaves no evidence, no witnesses, no bodies. Until now — a single body in a sealed vault, bearing a message addressed to Lena by name. The Cartels are no longer hiding. They're inviting her in. And the closer she gets to the truth, the more certain she becomes that someone she trusts has been playing both sides from the very beginning.",characters:"Detective Lena Drost, The Fixer, Commissioner Halvard",year:2024,pages:388,rating:4.6,reviews:173},
  {title:"The Lantern Keeper's Daughter",author:"Yuki Asano",genre:"children",img:"https://images.unsplash.com/photo-1504208434309-cb69f4fe52b0?w=600&q=80",summary:"Every night, old Thomas lights the lanterns along Fogmere Harbour so the fishing boats can find their way home. When he falls ill and ten-year-old Pip must light them alone, she discovers the lanterns don't just guide boats — they guide lost things of all kinds. Tonight, three unusual visitors need her help: a cloud that has forgotten the sky, a fox who has forgotten his name, and a letter that has been searching for its reader for forty-seven years.",characters:"Pip Thomas, The Cloud, The Fox",year:2023,pages:144,rating:4.9,reviews:612},
  {title:"Beneath Red Skies",author:"Kofi Mensah",genre:"adventure",img:"https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=600&q=80",summary:"When the skies above the Redlands turn crimson and stay that way, the desert communities know the great storms are coming. But teenage runner Amara has discovered a signal beneath the red sky — a frequency, a pattern. Following it will take her deep into the ruins of the settlement that was swallowed twenty years ago, where she believes her mother may still be alive. A breathless adventure about love, loss, and what we inherit from those who came before us.",characters:"Amara Sule, Kojo, Elder Yaa",year:2024,pages:356,rating:4.7,reviews:244},
  {title:"The Stitched Man",author:"Dara Osei",genre:"horror",img:"https://images.unsplash.com/photo-1542281286-9e0a16bb7366?w=600&q=80",summary:"Folklore says the Stitched Man walks the moors on moonless nights — assembled from scraps of other people, wearing their faces in rotation. Archivist Petra Holt arrives to document the legend and is assured by everyone it is only a story. Then she finds the sewing kit. Then the notebook. Then, on the third moonless night, she finds herself face to face with something that knows her name and is wearing the face of her sister, who has been dead for six years.",characters:"Petra Holt, The Stitched Man, Clara",year:2023,pages:298,rating:4.6,reviews:189},
  {title:"City of Falling Stars",author:"Mei Tanaka",genre:"sci-fi",img:"https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=600&q=80",summary:"In the floating city of Caelum, suspended above the clouds by technology no one fully understands anymore, engineer Ren has discovered a terrifying truth: the city is not hovering. It is still rising. And when it reaches the altitude marked in the forbidden blueprints she found, it will not be able to stop. Ren has seventy-two hours to find the override, convince people who have no reason to believe her, and dismantle three centuries of comfortable mythology.",characters:"Ren Koizumi, Governor Aldric, The Archivist Doll",year:2024,pages:412,rating:4.8,reviews:367},
];

export const reviews=[
  {name:"Zara M.",color:"#7C3AED",story:"The Dragon's Promise",stars:5,text:"Absolutely breathtaking. Priya Nair built a world so vivid I forgot I was reading. The dragon Auren is unlike any creature I've encountered in fiction — fierce, melancholic, and more human than most humans.",date:"April 2025"},
  {name:"Leo K.",color:"#1D4ED8",story:"The Last Starkeeper",stars:5,text:"This is what space opera should feel like. Lyra's journey across the Void made me feel genuinely afraid for her. The prose glows on the page — luminous imagery, tremendous emotional depth.",date:"March 2025"},
  {name:"Nadia F.",color:"#B91C1C",story:"Love in a Time of Static",stars:5,text:"I laughed, I sobbed, and I finished it at 2am unable to sleep. This book understood me. That's the only way I can describe it.",date:"May 2025"},
  {name:"Callum R.",color:"#065F46",story:"The Iron Compass",stars:5,text:"I read a lot of adventure fiction. The Iron Compass is not hollow. The Meridian is one of the most inventive fictional environments I've encountered, and Captain Rio deserves his own trilogy.",date:"April 2025"},
  {name:"Priya O.",color:"#9D174D",story:"Whispers in the Willows",stars:5,text:"I've read hundreds of mystery novels. This one genuinely surprised me. Twice. The atmosphere is exquisite and the twist is earned in a way that made me immediately reread the first chapter.",date:"February 2025"},
  {name:"Emi T.",color:"#92400E",story:"Buttons and the Bumblebee Prince",stars:5,text:"My six-year-old demanded three consecutive readings. My nine-year-old, who 'doesn't like books,' quietly picked it up the next morning. By page 12 he was laughing out loud.",date:"May 2025"},
];

export const botR={
  greet:["Welcome to LibraryHub. I'm Sage — part librarian, part oracle. 📚 Tell me what kind of story calls to you: a genre, a mood, a theme. I'll find the perfect match.","Hello, fellow reader. I'm Sage. Give me a genre, a mood, even a single word — I'll do the rest. 🌟"],
  fantasy:["For fantasy, begin with **The Dragon's Promise** by Priya Nair — sweeping, emotional, magnificently imagined. Or try **Echoes of Elara** for something more cerebral and mysterious. 🐉✨","Among our classics, **The Lord of the Rings** remains the foundation of all modern fantasy."],
  scifi:["For sci-fi, **The Last Starkeeper** is luminous space opera at its finest. For something more claustrophobic, **Signal Lost** will have you awake at 3am. 🚀 Or try Orwell's **1984** — more relevant than it has any right to be."],
  mystery:["**Whispers in the Willows** is our finest mystery — two timelines, one impossible suspect, an atmosphere you could drown in. For classic mystery, **The Adventures of Sherlock Holmes** is unmatched. 🔍"],
  horror:["**The Hollow Hours** is a masterclass in atmospheric dread — no jump scares, just creeping certainty that something is very wrong. **The Stitched Man** is equally chilling. 👻🕯️"],
  romance:["**Love in a Time of Static** is unlike most romance — built on grief, radio static, and two people who keep talking when they should have hung up. Or try Jane Austen's **Pride and Prejudice** — the standard all romance is measured against. 💌"],
  adventure:["**The Iron Compass** is our finest adventure — six misfits, one uncharted wilderness, a story that refuses to be only what it appears. **Beneath Red Skies** is a breathless runner-up. ⚔️"],
  children:["**Buttons and the Bumblebee Prince** is sheer joy. **The Lantern Keeper's Daughter** is equally wonderful — quiet, tender, and luminous. 🐝🌈"],
  dark:["For dark atmospheric reading: **The Hollow Hours**, **The Stitched Man**, **Whispers in the Willows**, or Orwell's **1984**. All exceptional in their own brand of darkness. 🕯️"],
  default:["Tell me more — what feeling are you chasing? Adventure, longing, dread, wonder, heartbreak, joy? Give me even a single word and I'll surprise you. 😊📚","What world do you want to escape into tonight? Give me a genre, a mood, or a colour — I'll do the rest. 🌟"],
};
